# simple github actions workflow to create a pyenv virtualenv and install requirements.txt
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pyenv
        run: |
          curl https://pyenv.run | bash
          export PATH="/home/runner/.pyenv/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
      - name: Eval pyenv and restart shell
        run: |
          export PATH="/home/runner/.pyenv/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          exec $SHELL
      - name: Create virtualenv
        run: |
          pyenv install 3.8.0
          pyenv virtualenv 3.8.0 deploy
          pyenv activate deploy
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy
        run: |
          python deploy.py
